# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/cmake-gui

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/dong/Workspace/dong/rtc/RTC_ImageProcess

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/dong/Workspace/dong/rtc/RTC_ImageProcess

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"component\" \"headers\" \"idl\" \"library\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/usr/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package
.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/usr/bin/cpack --config ./CPackSourceConfig.cmake /home/dong/Workspace/dong/rtc/RTC_ImageProcess/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dong/Workspace/dong/rtc/RTC_ImageProcess/CMakeFiles /home/dong/Workspace/dong/rtc/RTC_ImageProcess/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dong/Workspace/dong/rtc/RTC_ImageProcess/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) -f CMakeFiles/uninstall.dir/build.make CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named doxygen_doc

# Build rule for target.
doxygen_doc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 doxygen_doc
.PHONY : doxygen_doc

# fast build rule for target.
doxygen_doc/fast:
	$(MAKE) -f doc/CMakeFiles/doxygen_doc.dir/build.make doc/CMakeFiles/doxygen_doc.dir/build
.PHONY : doxygen_doc/fast

#=============================================================================
# Target rules for targets named ALL_IDL_TGT

# Build rule for target.
ALL_IDL_TGT: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ALL_IDL_TGT
.PHONY : ALL_IDL_TGT

# fast build rule for target.
ALL_IDL_TGT/fast:
	$(MAKE) -f idl/CMakeFiles/ALL_IDL_TGT.dir/build.make idl/CMakeFiles/ALL_IDL_TGT.dir/build
.PHONY : ALL_IDL_TGT/fast

#=============================================================================
# Target rules for targets named BasicDataType_TGT

# Build rule for target.
BasicDataType_TGT: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 BasicDataType_TGT
.PHONY : BasicDataType_TGT

# fast build rule for target.
BasicDataType_TGT/fast:
	$(MAKE) -f idl/CMakeFiles/BasicDataType_TGT.dir/build.make idl/CMakeFiles/BasicDataType_TGT.dir/build
.PHONY : BasicDataType_TGT/fast

#=============================================================================
# Target rules for targets named ExtendedDataTypes_TGT

# Build rule for target.
ExtendedDataTypes_TGT: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExtendedDataTypes_TGT
.PHONY : ExtendedDataTypes_TGT

# fast build rule for target.
ExtendedDataTypes_TGT/fast:
	$(MAKE) -f idl/CMakeFiles/ExtendedDataTypes_TGT.dir/build.make idl/CMakeFiles/ExtendedDataTypes_TGT.dir/build
.PHONY : ExtendedDataTypes_TGT/fast

#=============================================================================
# Target rules for targets named InterfaceDataTypes_TGT

# Build rule for target.
InterfaceDataTypes_TGT: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 InterfaceDataTypes_TGT
.PHONY : InterfaceDataTypes_TGT

# fast build rule for target.
InterfaceDataTypes_TGT/fast:
	$(MAKE) -f idl/CMakeFiles/InterfaceDataTypes_TGT.dir/build.make idl/CMakeFiles/InterfaceDataTypes_TGT.dir/build
.PHONY : InterfaceDataTypes_TGT/fast

#=============================================================================
# Target rules for targets named imProcessPort_TGT

# Build rule for target.
imProcessPort_TGT: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 imProcessPort_TGT
.PHONY : imProcessPort_TGT

# fast build rule for target.
imProcessPort_TGT/fast:
	$(MAKE) -f idl/CMakeFiles/imProcessPort_TGT.dir/build.make idl/CMakeFiles/imProcessPort_TGT.dir/build
.PHONY : imProcessPort_TGT/fast

#=============================================================================
# Target rules for targets named RTC_ImageProcess

# Build rule for target.
RTC_ImageProcess: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 RTC_ImageProcess
.PHONY : RTC_ImageProcess

# fast build rule for target.
RTC_ImageProcess/fast:
	$(MAKE) -f src/CMakeFiles/RTC_ImageProcess.dir/build.make src/CMakeFiles/RTC_ImageProcess.dir/build
.PHONY : RTC_ImageProcess/fast

# Manual pre-install relink rule for target.
RTC_ImageProcess/preinstall:
	$(MAKE) -f src/CMakeFiles/RTC_ImageProcess.dir/build.make src/CMakeFiles/RTC_ImageProcess.dir/preinstall
.PHONY : RTC_ImageProcess/preinstall

#=============================================================================
# Target rules for targets named RTC_ImageProcessComp

# Build rule for target.
RTC_ImageProcessComp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 RTC_ImageProcessComp
.PHONY : RTC_ImageProcessComp

# fast build rule for target.
RTC_ImageProcessComp/fast:
	$(MAKE) -f src/CMakeFiles/RTC_ImageProcessComp.dir/build.make src/CMakeFiles/RTC_ImageProcessComp.dir/build
.PHONY : RTC_ImageProcessComp/fast

# Manual pre-install relink rule for target.
RTC_ImageProcessComp/preinstall:
	$(MAKE) -f src/CMakeFiles/RTC_ImageProcessComp.dir/build.make src/CMakeFiles/RTC_ImageProcessComp.dir/preinstall
.PHONY : RTC_ImageProcessComp/preinstall

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... list_install_components"
	@echo "... package"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... uninstall"
	@echo "... doxygen_doc"
	@echo "... ALL_IDL_TGT"
	@echo "... BasicDataType_TGT"
	@echo "... ExtendedDataTypes_TGT"
	@echo "... InterfaceDataTypes_TGT"
	@echo "... imProcessPort_TGT"
	@echo "... RTC_ImageProcess"
	@echo "... RTC_ImageProcessComp"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

